### ISSUE TITLE
Overriden frontend html files from inside 'web/template' directory isn't being detected yet

### ISSUE THREAD

**Issue by hostep** [AmpersandHQ/ampersand-magento2-upgrade-patch-helper#1]
Hi

Big thanks for open sourcing this tool!

If I compare it with the output of my own crappy script to detect changes between 2 different versions of Magento, I notice one difference when doing a diff in between Magento 2.2.6 and 2.2.7 for frontend overridden files.

My script detects this file as overwritten in one of our projects, but this tool doesn't seem to support this yet: `Magento_Checkout/web/template/summary/item/details.html`  ([2.2.6 version](https://github.com/magento/magento2/blob/2.2.6/app/code/Magento/Checkout/view/frontend/web/template/summary/item/details.html) vs [2.2.7 version](https://github.com/magento/magento2/blob/2.2.7/app/code/Magento/Checkout/view/frontend/web/template/summary/item/details.html))

Would be nice if this tool could also detect such files.

Thanks again! :)

**Comment by convenient** [comment]
Thanks @hostep

Firstly let's make sure you've got your `vendor.patch` set up properly, otherwise we won't be scanning for anything.

If you run the following command you should get the same output?
```bash
grep -A11 "diff -ur vendor_orig/magento/module-checkout/view/frontend/web/template/summary/item/details.html" vendor.patch
```
```diff
diff -ur vendor_orig/magento/module-checkout/view/frontend/web/template/summary/item/details.html vendor/magento/module-checkout/view/frontend/web/template/summary/item/details.html
--- vendor_orig/magento/module-checkout/view/frontend/web/template/summary/item/details.html	2018-06-14 15:31:20.000000000 +0100
+++ vendor/magento/module-checkout/view/frontend/web/template/summary/item/details.html	2018-11-19 12:00:38.000000000 +0000
@@ -12,7 +12,7 @@
 
     <div class="product-item-inner">
         <div class="product-item-name-block">
-            <strong class="product-item-name" data-bind="text: $parent.name"></strong>
+            <strong class="product-item-name" data-bind="html: $parent.name"></strong>
             <div class="details-qty">
                 <span class="label"><!-- ko i18n: 'Qty' --><!-- /ko --></span>
                 <span class="value" data-bind="text: $parent.qty"></span>
```

Secondly could you give me full path of the override that was missed? I'm aware this may have client info in it, so please fuzz out the data with `foo/bar/baz` or whatever

**Comment by hostep** [comment]
Sure

So the grep command gives me exactly what you've outputted, so that's already good.

And the full path to the override is: `app/design/frontend/Vendor/theme/Magento_Checkout/web/template/summary/item/details.html`

**Comment by convenient** [comment]
Hey,

To override this template in the web directory did you have to define anything in `requirejs-config.js` like https://magento.stackexchange.com/a/121702/17176?

I'm just trying to replicate this method of override before targeting it and it's not working off the bat.

Thanks

**Comment by hostep** [comment]
Hmm

It seems to work over here, without an entry in the `requirejs-config.js`
Stackoverflow seems to confirm: https://magento.stackexchange.com/a/219727/2911

Make sure to flush your caches, and the `app/design/frontend/Vendor/theme/Magento_Checkout/web/template/summary/item/details.html` file is only used in the checkout, not in the cart.

<img width="1249" alt="screen shot 2018-12-05 at 13 32 09" src="https://user-images.githubusercontent.com/85479/49514052-2fc32800-f893-11e8-9d10-6630eee1ae5c.png">

If you want, I can try to setup an example on a clean Magento installation and not using this project I'm currently using, I don't think our frontend developers are doing anything strange here (can't find it at least), so I assume it works like this out of the box in Magento, but to be certain we probably need to do this on a clean installation.

**Comment by convenient** [comment]
Thanks @hostep I'll give this a whirl 👍

**Comment by hostep** [comment]
I can confirm that it find the overridden `.html` file now, excellent work! :)

**Comment by hostep** [comment]
I performed a more elaborate test and compared Magento 2.2.0 to 2.2.7, and for some reason, this override isn't being detected: `app/design/frontend/Vendor/theme/Magento_Ui/web/templates/block-loader.html`

I'll see if I can debug a bit to what goes wrong.

(there's also another type of file which is missing, for which I'll open another issue, since it's not related to this one)

**Comment by hostep** [comment]
Ok, the issue with that html file from `Magento_UI` is because Magento is being inconsistent again, where they mostly use the directory name "template", but also sometimes use "template**s**", but only in 2 modules:
```bash
$ find vendor/magento -type d -path '*web/templates'
vendor/magento/module-theme/view/frontend/web/templates
vendor/magento/module-ui/view/frontend/web/templates
vendor/magento/module-ui/view/adminhtml/web/templates
vendor/magento/module-ui/view/base/web/templates
```

I've verified that these files can be overridden by copying the file `vendor/magento/module-ui/view/frontend/web/templates/group/group.html` to `app/design/frontend/Vendor/theme/Magento_Ui/web/templates/group/group.html`, adding some gibberish to the top, clearing all possible frontend caches, and going to the checkout, where this file is being used.

The fix I came up with for this module is to replace:
```php
$templatePart = ltrim(substr($file, stripos($file, '/web/template/')), '/');
```
with:
```php
$templatePart = ltrim(preg_replace('#^.+/web/templates?/#i', '', $file), '/');
```
which will both match "template" and "template**s**" in `Ampersand\PatchHelper\Helper\PatchOverrideValidator::validateWebTemplateHtml`

**Comment by convenient** [comment]
@hostep  I _just_ came to the same conclusion and updated with https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/commit/a0b2c0c79bbbdc3482cb7e4e0f18cd3ea94a5d8e#diff-52223308445703a86635bbaff448d6e7R297

Your modification is much better though, do you want to raise a PR into the branch or are you happy for me to copy paste in?

**Comment by hostep** [comment]
Feel free to copy it in if you want, I don't mind at all :)

**Comment by convenient** [comment]
@hostep I've done some rebasing, can you do one final check of https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/pull/4 before I merge into `master`?

**Comment by hostep** [comment]
Ok, I'll try to review later today, thanks for the changes!

**Comment by convenient** [comment]
Brill, let me know.

**Comment by hostep** [comment]
Hi @convenient 

I've tested again and it looks perfect right now, all overridden `.html` are found, so can be merged in my opinion :)

Thanks again!

**Comment by convenient** [comment]
Great stuff @hostep. I've merged this in and the tests are going green in our private travis setup 🤜 

Thank you very much for contributing and for raising the other issues, I'll review them.

Do you think you'll be using this tool going forward? Any other features / scans missing from your current script?

**Comment by hostep** [comment]
And another idea which just popped into my head: it would maybe also be nice if this tool could also be used for non-Magento module updates.
For example: we have some of our own modules installed using composer, and sometimes a file of those modules is being overridden in the theme of the project or in some other module in `app/code` specific to the project (this can also happen with 3rd party modules). If you then update one of those modules to a newer version and one of those overrides is also changed, then it would be nice if this could also be reported.
The tricky bit will be to detect what in `vendor` is a Magento module and what is not (maybe search for `registration.php` or something like that?)

About:
> Currently I don't quite like the manual copying of the vendor directory and creating a diff, but I currently have no better idea to do this in a smarter way.

I'm just also realising (but this will be pretty complex as well) that this could maybe be turned into a composer module, which triggers when a package is updated, and takes a snapshot before and after the update and then does its magic, but that will make the composer update process very heavy to execute I guess.

**Comment by convenient** [comment]
Hey @hostep 

I've raised a few issues (#5 #6) based on your feedback. I believe that these issues are achievable in the short-mid term, the plugin one seems like the groundwork is already there (after some larger refactoring of how we parse the patch file).

Your other suggestions are interesting so feel free to raise an issue with any details if you have them.

Your assistance is much appreciated.
