### ISSUE TITLE
Run Travis tests automatically

### ISSUE THREAD

**Issue by peterjaap** [AmpersandHQ/ampersand-magento2-upgrade-patch-helper#10]
I read your last line in the readme;

> They do not run automatically in travis as you cannot run composer create-project --repository-url=https://repo.magento.com/ without providing and exposing an access token to the world.

Fooman provided an unauthenticated mirror for the Magento 2 codebase, so you might be able to use that;
https://store.fooman.co.nz/blog/no-authentication-needed-magento-2-mirror.html

**Comment by convenient** [comment]
This looks really interesting, thanks!
