### ISSUE TITLE
Not Compatible with Magento 2.4.6-p1

### ISSUE THREAD

**Issue by NathanDayFE** [AmpersandHQ/ampersand-magento2-upgrade-patch-helper#102]
I haven't looked at the base version of Magento 2.4.6 but p1 requires `symfony/console:^5.4` which isn't compatible with this module

I haven't yet looked into what is added/changed between the major version of `symfony/console` so it may just be a case of allowing `^5.0` as a lot of other modules seem to be doing

**Comment by NathanDayFE** [comment]
@convenient this issue can probably be closed, as I was not using the tool as intended. Rather than cloning the repository I was installing via composer. When doing that the symfony console versions conflict. reverting to the official method of cloning works fine.

**Comment by convenient** [comment]
@NathanDayFE Ahh thank you. Yes bringing this in as a dependency of magento means stricter comparisons. 

Using the clone methodology I can support a wider array of magento versions from the one codebase, which can be helpful when you get a magento 2.2 project that needs upgraded to 2.3 before hitting 2.4 etc. It's not pleasant but these scenarios can happen so I try to keep the tool as flexible as possible 👍
