### ISSUE TITLE
An adminhtml xml file is detected as being overridden in a frontend theme

### ISSUE THREAD

**Issue by hostep** [AmpersandHQ/ampersand-magento2-upgrade-patch-helper#2]
This happens both on the `master` and `fix-template-detection-issue-1` branches.
Tested when comparing Magento 2.2.0 to 2.2.7

The tool reports the core file: `vendor/magento/module-sales/view/adminhtml/layout/sales_order_view.xml` to be overridden/extended by `app/design/frontend/Vendor/theme/Magento_Sales/layout/sales_order_view.xml`

I don't think this is correct, since a frontend theme can't override files from the adminhtml.

**Comment by convenient** [comment]
@hostep I believe that I have corrected this issue in c6310069b38af80926fedd7a08a6c3fcb6f05b73

**Comment by hostep** [comment]
Can confirm that it's fixed, thanks!
