### ISSUE TITLE
Plugin detection with virtual types can give php warnings

### ISSUE THREAD

**Issue by hostep** [AmpersandHQ/ampersand-magento2-upgrade-patch-helper#35]
I'm working on upgrading a shop from Magento 2.2.7 to 2.3.5-p2 and I noticed the following output:
```
$ bin/patch-helper.php analyse --sort-by-type ~/Projects/magento2/some-project/
PHP Warning:  Invalid argument supplied for foreach() in src/Ampersand/PatchHelper/Helper/PatchOverrideValidator.php on line 254

Warning: Invalid argument supplied for foreach() in src/Ampersand/PatchHelper/Helper/PatchOverrideValidator.php on line 254
+--------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+
| Type                     | Core                                                                                                         | To Check                                                                                                                 |
+--------------------------+--------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+
...
```

So something goes wrong with fetching the class methods from a certain plugin [over here](https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/5885d68f4c29c77c7ee7be6e7d6de03df5e57aec/src/Ampersand/PatchHelper/Helper/PatchOverrideValidator.php#L254).

The contents of the `$plugin` variable at that point was `stockedProductsFilterPluginFix`, it looks like this is not a class name but a reference to a virtualtype, comming from the amasty elastic search module (version 1.9.1):

```xml
<virtualType name="stockedProductsFilterPluginFix" type="Amasty\ElasticSearch\PluginFix\EmptyPlugin">
    <arguments>
        <argument name="instanceFactory" xsi:type="object">StockedProductsFilterPluginFactory</argument>
    </arguments>
</virtualType>

<virtualType name="StockedProductsFilterPluginFactory" type="Amasty\ElasticSearch\PluginFix\PluginFactory">
    <arguments>
        <argument name="instanceName" xsi:type="string">Magento\Elasticsearch\Model\Indexer\Plugin\StockedProductsFilterPlugin</argument>
    </arguments>
</virtualType>

<type name="Magento\CatalogSearch\Model\Indexer\Fulltext\Action\DataProvider">
    <plugin name="stockedProductsFilterPlugin" type="stockedProductsFilterPluginFix"/>
</type>

```

So in this case, it should probably run the function `get_class_methods` on the class `Amasty\ElasticSearch\PluginFix\EmptyPlugin`, right?

Thanks!

**Comment by convenient** [comment]
@hostep that makes sense

https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/5885d68f4c29c77c7ee7be6e7d6de03df5e57aec/src/Ampersand/PatchHelper/Helper/PatchOverrideValidator.php#L210-L235

This section of code is responsible for getting the plugin data from the config. You can see it has fields like `instance` and `disabled`. I had assumed that `instance` would work at all times but it seems not to for virtual types.

It would be good to see what values we have for the `$pluginConf` for the affected plugin
