### ISSUE TITLE
Any way to make it not depend on a database?

### ISSUE THREAD

**Issue by peterjaap** [AmpersandHQ/ampersand-magento2-upgrade-patch-helper#43]
We're currently exploring whether we can run this tool in a scheduled pipeline to automate these steps;

```
    - composer install
    - mv vendor vendor_orig
    - composer require magento/product-community-edition 2.4.1 --no-update
    - composer --profile update
    - bin/magento set:up
    - diff -ur vendor_orig/ vendor/ > vendor.patch
    - cd ampersand-magento2-upgrade-patch-helper
    - php bin/patch-helper.php analyse ../ --auto-theme-update 0 --sort-by-type ../patch-helper-output.txt
```

This way, we could let our pipeline do the heavy lifting and commit the result to a separate branch, from where a developer can walk through the `patch-helper-output.txt` file. One of the things we're running into is that we need a database because the upgrade patch helper assumes a running Magento install. This isn't an issue per se, but we'd rather not. Is there any way we could make the patch helper run on just code, and no db?

**Comment by convenient** [comment]
@peterjaap  AFAIK this needs a running magento instance as you can have theme configuration in the database

https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/573de328b40eae2153a14bfa19d05063ad680f88/src/Ampersand/PatchHelper/Helper/Magento2Instance.php#L83

I guess you could try hacking out some of the values in the constructor in that class to see which bits themselves actually trigger the database? 

Do you have a trace where it first complains about the missing database? Perhaps we could run a stripped down version with a flag?

**Comment by peterjaap** [comment]
Here's the trace for when it can't connect to a database;

```
In ResourceConnection.php line 149:                                                                       
                                                                                                          
  [DomainException]                                                                                       
  Connection "default" is not defined                                                                     
                                                                                                          
                                                                                                          
Exception trace:                                                                                          
 () at /data/client/magento2/vendor/magento/framework/App/ResourceConnection.php:149     
 Magento\Framework\App\ResourceConnection->getConnectionByName() at /data/client/magento2/generated/code/Magento/Framework/App/ResourceConnection/Interceptor.php:50
 Magento\Framework\App\ResourceConnection\Interceptor->getConnectionByName() at /data/client/magento2/vendor/magento/framework/App/ResourceConnection.php:97
 Magento\Framework\App\ResourceConnection->getConnection() at /data/client/magento2/generated/code/Magento/Framework/App/ResourceConnection/Interceptor.php:24
 Magento\Framework\App\ResourceConnection\Interceptor->getConnection() at /data/client/magento2/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php:333
 Magento\Framework\Model\ResourceModel\Db\AbstractDb->getConnection() at /data/client/magento2/vendor/magento/framework/Module/ModuleResource.php:86
 Magento\Framework\Module\ModuleResource->getDbVersion() at /data/client/magento2/vendor/magento/framework/Module/DbVersionInfo.php:58
 Magento\Framework\Module\DbVersionInfo->isSchemaUpToDate() at /data/client/magento2/vendor/magento/framework/Module/DbVersionInfo.php:103
 Magento\Framework\Module\DbVersionInfo->getDbVersionErrors() at /data/client/magento2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php:119
 Magento\Framework\Module\Plugin\DbStatusValidator->getGroupedDbVersionErrors() at /data/client/magento2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php:53
 Magento\Framework\Module\Plugin\DbStatusValidator->beforeDispatch() at /data/client/magento2/vendor/magento/framework/Interception/Interceptor.php:121
 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() at /data/client/magento2/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:69
 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() at /data/client/magento2/vendor/magento/framework/Interception/Interceptor.php:135
 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() at /data/client/magento2/vendor/magento/framework/Interception/Interceptor.php:153
 Magento\Framework\App\FrontController\Interceptor->___callPlugins() at /data/client/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php:26
 Magento\Framework\App\FrontController\Interceptor->dispatch() at /data/client/magento2/vendor/magento/framework/App/Http.php:116
 Magento\Framework\App\Http->launch() at /data/client/magento2/vendor/magento/framework/Interception/Interceptor.php:58
 Magento\Framework\App\Http\Interceptor->___callParent() at /data/client/magento2/vendor/magento/framework/Interception/Interceptor.php:138
 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() at /data/client/magento2/vendor/justbetter/magento2-sentry/Plugin/GlobalExceptionCatcher.php:43
 JustBetter\Sentry\Plugin\GlobalExceptionCatcher->aroundLaunch() at /data/client/magento2/vendor/magento/framework/Interception/Interceptor.php:135
 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() at /data/client/magento2/vendor/magento/framework/Interception/Interceptor.php:153
 Magento\Framework\App\Http\Interceptor->___callPlugins() at /data/client/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php:26
 Magento\Framework\App\Http\Interceptor->launch() at /data/ampersand-magento2-upgrade-patch-helper/src/Ampersand/PatchHelper/Helper/Magento2Instance.php:74
 Ampersand\PatchHelper\Helper\Magento2Instance->__construct() at /data/ampersand-magento2-upgrade-patch-helper/src/Ampersand/PatchHelper/Command/AnalyseCommand.php:54
 Ampersand\PatchHelper\Command\AnalyseCommand->execute() at /data/ampersand-magento2-upgrade-patch-helper/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /data/ampersand-magento2-upgrade-patch-helper/vendor/symfony/console/Application.php:953
 Symfony\Component\Console\Application->doRunCommand() at /data/ampersand-magento2-upgrade-patch-helper/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /data/ampersand-magento2-upgrade-patch-helper/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /data/ampersand-magento2-upgrade-patch-helper/bin/patch-helper.php:10

```

**Comment by peterjaap** [comment]
So the `Magento2Instance` helper instantiates a Magento instance, which needs a database connection to a Magento database.

This has 2 main functions;
- Provide the `PatchOverrideValidator` with the global config and area configs to build up a list of DI preferences
- Provide the `PatchOverrideValidator` with a list of custom themes to validate files mentioned in the patch file against. This also uses Magento's MinificationResolver to resolve paths of minified files.

In order to make it not depend on the database (or, more specifically; an instantiated Magento install), we'd need to parse the DI configuration ourselves, parse the theme configuration sourselves and copy the ogic of the MinificationResolver. That's quite a bit of work and I'm not sure we're even able to get a decent approximation of how Magento handles it.

**Comment by peterjaap** [comment]
Another approach would be to get the necessary data from a running instance (i.e. production) and save it into a file, which serves as input for the patch helper. The downside is that the data could be outdated when used.

**Comment by peterjaap** [comment]
Oh here's a thought; when running unit tests, a database connection is not needed but it does instantiate Magento. Maybe we can hook into that?

**Comment by convenient** [comment]
>ourselves and recreate the logic of the MinificationResolver. That's quite a bit of work and I'm not sure we're even able to get a decent approximation of how Magento handles it.

Yes i am keen to hook into the magento functionality as much as possible to ensure we don't end up deviating from the magento core and missing plugins/preferences.  I wonder if the `MinificationResolver` actually needs the database so long as its constructed with the right theme information stored in the config?

>Another approach would be to get the necessary data from a running instance (i.e. production) and save it into a file, which serves as input for the patch helper. The downside is that the data could be outdated when used.

I am happy to support this kind of thing so long as it is not the default mode for this tool. 

>Oh here's a thought; when running unit tests, a database connection is not needed but it does instantiate Magento. Maybe we can hook into that?

@peterjaap That makes sense. Also it is possible to run `php bin/magento` and some commands when you do not have a database, I think these commands for installing magento and other things may hook into `di.xml`? I am not certain that you _need_ a database in order to do this part?

**Comment by convenient** [comment]
And another thought. Magento2 supports dumping required configuration for building the site into `config.php` i think, so that you can build the full production asset without connecting to the database.

Perhaps we can look into that to see how that works, maybe that will be a way forward on figuring out the themes / etc without the database?

**Comment by peterjaap** [comment]
I just discovered @vinai found a way to instantiate Magento without a database [by hijacking the integration test suite](https://github.com/mage2tv/magento-cache-clean/search?q=integration-test). However, I have no idea how since I know about us much Clojure as I know about football, i.e. nothing.

**Comment by convenient** [comment]
That's very interesting, I should have tagged you but didn't think. But I recently merged https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/pull/47 which removes the call to `launch` entirely.

Do you still see the same issues running this without a DB?

**Comment by peterjaap** [comment]
> That's very interesting, I should have tagged you but didn't think. But I recently merged #47 which removes the call to `launch` entirely. I am not certain we were calling `launch` for any definite reason other than thats how the developer who first worked on this script bootstrapped magento 🤷‍♂️
> 
> Do you still see the same issues running this without a DB?

Oh wow that was all? 😃 I'll test it asap!

**Comment by peterjaap** [comment]
Omg it works! This opens the door to many interesting possibilities. Thanks!!

**Comment by convenient** [comment]
@peterjaap woo!

![its alive](https://media.giphy.com/media/d3Kq5w84bzlBLVDO/giphy.gif)
