### ISSUE TITLE
Issue in bootstrapping Magento with 2.3.6-p1

### ISSUE THREAD

**Issue by hostep** [AmpersandHQ/ampersand-magento2-upgrade-patch-helper#45]
Hiya

When trying to run this tool when analysing an upgrade from Magento 2.3.6 to 2.3.6-p1, I'm getting the following error:

```
$ bin/patch-helper.php analyse /some-project -vvv

In PhpCookieManager.php line 397:

  [Magento\Framework\Stdlib\Cookie\FailureToSendException]
  The cookie with "private_content_version" cookieName couldn't be sent. Please try again later.


Exception trace:
 () at /some-project/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php:397
 Magento\Framework\Stdlib\Cookie\PhpCookieManager->setCookieSameSite() at /some-project/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php:183
 Magento\Framework\Stdlib\Cookie\PhpCookieManager->setCookie() at /some-project/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php:135
 Magento\Framework\Stdlib\Cookie\PhpCookieManager->setPublicCookie() at /some-project/vendor/magento/framework/App/PageCache/Version.php:87
 Magento\Framework\App\PageCache\Version->process() at /some-project/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:67
 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() at /some-project/vendor/magento/framework/Interception/Interceptor.php:135
 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() at /some-project/vendor/magento/framework/Interception/Interceptor.php:153
 Magento\Framework\App\FrontController\Interceptor->___callPlugins() at /some-project/generated/code/Magento/Framework/App/FrontController/Interceptor.php:26
 Magento\Framework\App\FrontController\Interceptor->dispatch() at /some-project/vendor/magento/framework/App/Http.php:116
 Magento\Framework\App\Http->launch() at src/Ampersand/PatchHelper/Helper/Magento2Instance.php:74
 Ampersand\PatchHelper\Helper\Magento2Instance->__construct() at src/Ampersand/PatchHelper/Command/AnalyseCommand.php:54
 Ampersand\PatchHelper\Command\AnalyseCommand->execute() at vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at vendor/symfony/console/Application.php:953
 Symfony\Component\Console\Application->doRunCommand() at vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at bin/patch-helper.php:10

analyse [-a|--auto-theme-update [AUTO-THEME-UPDATE]] [--sort-by-type] [--vendor-namespaces [VENDOR-NAMESPACES]] [--php-strict-errors] [--] <project>
```

If you haven't got access yet to Magento 2.3.6-p1, it will be [released](https://devdocs.magento.com/release/) to the public on 9 February.

It looks like Magento gets bootstrapped in a http context by this tool and Magento 2.3.6-p1 comes with support for [SameSite cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) and while it tries to set it, it causes an error because it's not an actually http request, if I understand it correctly.

Not sure if the error is in this tool or a new bug in Magento 2.3.6-p1

**Comment by hostep** [comment]
I can get it working again by removing this line:
https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/3fb65d9993e2fa42738e305f58c5b913ff230d13/src/Ampersand/PatchHelper/Helper/Magento2Instance.php#L67

However, from the comments above that line, it seems like it might be needed for some very specific case.

The reason why removing the line works, is because of this check in Magento's core: https://github.com/magento/magento2/blob/2.3.6/lib/internal/Magento/Framework/App/PageCache/Version.php#L78, it won't try to set that cookie

**Comment by convenient** [comment]
I am trying to recall why we bootstrapped this in http context, i think it may have been to hook into the frontend minification etc 🤔

Does this issue occur for you when the pagecache is disabled @hostep ?

**Comment by hostep** [comment]
Sorry for the lack of feedback, I'll give it a try tomorrow.

(got sidetracked a bit by something which took my by surprise, Magento 2.3.6-p1 crashes on PHP 7.2, so make sure you're on 7.3 before upgrading)

**Comment by hostep** [comment]
Okay, results: disabling full page cache does not solve the problem.

Switching to the [fix-new-magento-2-3-6-1](https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/tree/fix-new-magento-2-3-6-1) branch does fix it, as well as the new [PR](https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/pull/46) you just created

**Comment by convenient** [comment]
This is now resolved in https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/pull/47
