### ISSUE TITLE
Validate non-core magento dependencies

### ISSUE THREAD

**Issue by convenient** [AmpersandHQ/ampersand-magento2-upgrade-patch-helper#5]
See todo here https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/v1.2.0/src/Ampersand/PatchHelper/Helper/PatchOverrideValidator.php#L133

And comment here https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/issues/1#issuecomment-445047204

There's not that much of a difference between updating magento core, and updating a third party magento module.

It would be good if we could make this tool scan for overrides to any magento2 module or set of modules.

There's a few places where the code is actively filtering for `Magento` that would have to be refactored.

**Comment by peterjaap** [comment]
So much +1

**Comment by govereem** [comment]
Would be nice +1

**Comment by convenient** [comment]
Thanks for the interest in this. I have a lot going on at the moment outside of software so will not be able to look at this for the foreseeable future. I would definitely be able to engage in any Pull Request that gets opened up though.

**Comment by peterjaap** [comment]
There's been a bit of work done over here; https://github.com/AW3i/ampersand-magento2-upgrade-patch-helper/tree/check-custom-modules

Unfortunately he refactored it as a Magento 2 extension so you'll need to test it like this;

```
composer config repositories.patch-helper vcs git@github.com:AW3i/ampersand-magento2-upgrade-patch-helper.git
composer require ampersand/magento2-upgrade-patch-helper:dev-check-custom-modules
bin/magento set:up
bin/magento ampersand:analyse --project . --sort-by-type
```
