### ISSUE TITLE
the report show 0 items 

### ISSUE THREAD

**Issue by onlinebizsoft** [AmpersandHQ/ampersand-magento2-upgrade-patch-helper#59]
For some reasons I couldn't get it working
- At first, I wanted to make a quick check on report of preference, plugin, PHTML/HTML/JS but an empty vendor.patch doesn't work so I have made a test modification and generate a non-empty vendor.patch so it can pass the validation for vendor.patch
- Now I get the empty report
You should review the above 0 items alongside /path/to/magento/vendor_files_to_check.patch
(the Magento installation is a fully working test site and has database connection)

Where should I look at? My site is 2.4.3 and I have the magefan conflict detector working well.

**Comment by onlinebizsoft** [comment]
Ah sorry for silly question. Now I understand the idea is just checking and list items to be reviewed which has relation to the difference between 2 versions 

Is there anyway to make a setting to allow to report all overrides without limiting to the difference between 2 versions? It would be helpful to have an overview of what the developers are doing.

**Comment by convenient** [comment]
> but an empty vendor.patch doesn't work

Yeah the entire point of this tool is to isolate in on only things that have changed in the upgrade that you have also customised, so that you can do less work during each upgrade.

It was never really designed to give a full overview of every change in the entire system :/

I guess you could spoof the system into maybe thinking that every file had been added by doing something like this 

```
$ rm -rf vendor vendor_orig
$ composer install
$ mkdir vendor_orig
$ diff -ur -N vendor_orig/ vendor/ > vendor.patch
```

The `-N` should show everything as a new file which may trick it into running through and producing full output.

**Comment by onlinebizsoft** [comment]
@convenient except a big file vendor.patch (500MB) then everything seems to work :) I will inspect the result and let you know if anything is wrong.

**Comment by onlinebizsoft** [comment]
Maybe a bug ?
![image](https://user-images.githubusercontent.com/22501570/134698821-4827dfbc-8cf9-4a78-9580-2602051465bf.png)

**Comment by convenient** [comment]
@onlinebizsoft Looks like i'm matching against the module correctly for this override, but matching the end of `default.xml` when i should be looking for `/default.xml` very likely.

Yes a bug, can you pop it on a separate issue please?

**Comment by onlinebizsoft** [comment]
@convenient Done but I think I found another "bug", the way you detect "override" for phtml/js/html would be correct but it is wrong term for layout XML.
Referring to https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/layout-extend.html -> it should be "Extending layout"
While overriding layout would be inside "override" folder and seems to have a few user cases (base,...) https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/layout-override.html

**Comment by convenient** [comment]
Closing as issue in #60 is tracked
