### ISSUE TITLE
Possibility to open three-file-diff viewer directly from the output

### ISSUE THREAD

**Issue by norgeindian** [AmpersandHQ/ampersand-magento2-upgrade-patch-helper#70]
Firstly: Thanks a lot for developing this awesome helper. We use it for every Magento update, and it makes our live so much easier!
When I now have the output of which files I shall check, I get through them one by one and open the diff viewer between the override / preference and the Magento Core file.
Sometimes, if I'm still not sure, if the changes are needed, I open the Core file in the `vendor_orig` folder and check out the three-file-diff.
Do you see any good way of having that directly as a possibility?
Maybe with a clickable link, which opens that view?
I saw, that PHPStorm offers some CLI approach: https://www.jetbrains.com/help/phpstorm/command-line-differences-viewer.html
For this, we would need the paths of all three files, which might be a bit difficult.
What do you think?

**Comment by convenient** [comment]
Hey @norgeindian 

Thanks for the issue.

Currently this tooling is pretty light on what you do with the output `vendor_files_to_check.patch` and the output from the CLI command. Having something clickable and actually interactable isn't something I'm planning on working on any time soon.

However, it does sound more like the kind of thing provided by @peterjaap and his tool https://github.com/elgentos/magento2-upgrade-gui#screenshots , have you given it a look and seen if it does what you need? 


>For this, we would need the paths of all three files, which might be a bit difficult.
So from the patchfile itself we have old/new path, but not override path when it is a PHP class.

Perhaps some changes could be made here (and similar for the plugin) to maybe use reflection and the object manager to instantiate the class, then get the filepath. and put that in the output instead? This could be gated with some `--to-check-show-filepaths` or something perhaps?

https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/7c0e61803a85c8f38f0215684578f86956f0a9b4/src/Ampersand/PatchHelper/Helper/PatchOverrideValidator.php#L192

**Comment by peterjaap** [comment]
@convenient I solve that by dumping the composer classmap with `composer dump --classmap-authoritative`, this will give you a mapping of the classname to the file.

**Comment by convenient** [comment]
@norgeindian @peterjaap It seems getting actual filepaths are pretty reasonable

https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/compare/convert-class-names-to-filepaths?expand=1

I didn't bother putting it behind a flag as this was a quick test, but seems simple enough.

Is this the kind of thing you need? Would it make sense to dump it into a different/new column on the table if the flag is present? 

```
| Override (phtml/js/html) | vendor/magento/module-customer/view/frontend/email/password_reset_confirmation.html   | app/design/frontend/Ampersand/theme/Magento_Customer/email/password_reset_confirmation.html |
| Override (phtml/js/html) | vendor/magento/module-sales/view/frontend/layout/sales_order_print.xml                | app/design/frontend/Ampersand/theme/Magento_Sales/layout/sales_order_print.xml              |
| Override (phtml/js/html) | vendor/magento/module-ui/view/base/web/templates/grid/masonry.html                    | app/design/frontend/Ampersand/theme/Magento_Ui/web/templates/grid/masonry.html              |
| Plugin                   | vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php                           | app/code/Ampersand/Test/Plugin/PhpCookieManager.php (beforeSetPublicCookie)                 |
| Plugin                   | vendor/magento/module-adobe-ims/Model/UserProfile.php                                 | app/code/Ampersand/Test/Plugin/AdobeImsUserProfile.php (afterGetUpdatedAt)                  |
| Plugin                   | vendor/magento/module-adobe-ims/Model/UserProfile.php                                 | app/code/Ampersand/Test/Plugin/AdobeImsUserProfile.php (aroundGetUpdatedAt)                 |
| Plugin                   | vendor/magento/module-adobe-ims/Model/UserProfile.php                                 | app/code/Ampersand/Test/Plugin/AdobeImsUserProfile.php (beforeGetUpdatedAt)                 |
| Plugin                   | vendor/magento/module-adobe-ims/Model/UserProfile.php                                 | app/code/Ampersand/Test/Plugin/AdobeImsUserProfileVirtual.php (afterGetUpdatedAt)           |
| Plugin                   | vendor/magento/module-adobe-ims/Model/UserProfile.php                                 | app/code/Ampersand/Test/Plugin/AdobeImsUserProfileVirtual.php (aroundGetUpdatedAt)          |
| Plugin                   | vendor/magento/module-adobe-ims/Model/UserProfile.php                                 | app/code/Ampersand/Test/Plugin/AdobeImsUserProfileVirtual.php (beforeGetUpdatedAt)          |
| Preference               | vendor/ampersand/upgrade-patch-helper-test-module/src/module/Api/ExampleInterface.php | app/code/Ampersand/Test/Model/Example.php                                                   |
| Preference               | vendor/ampersand/upgrade-patch-helper-test-module/src/module/Model/SomeClass.php      | app/code/Ampersand/Test/Model/ThirdPartyClass.php                                           |
| Preference               | vendor/magento/framework/Locale/Format.php                                            | app/code/Ampersand/Test/Model/Locale/Format.php                                             |
| Preference               | vendor/magento/module-advanced-pricing-import-export/Model/Export/AdvancedPricing.php | app/code/Ampersand/Test/Model/Admin/Export/AdvancedPricing.php                              |
| Preference               | vendor/magento/module-weee/Model/Total/Quote/Weee.php                                 | app/code/Ampersand/Test/Model/Admin/Total/Quote/Weee.php                                    |
| Preference               | vendor/magento/module-weee/Model/Total/Quote/Weee.php                                 | app/code/Ampersand/Test/Model/Frontend/Total/Quote/Weee.php                                 |
| Preference               | vendor/magento/module-weee/Model/Total/Quote/Weee.php                                 | app/code/Ampersand/Test/Model/Total/Quote/Weee.php                                          |
| Queue consumer added     | vendor/magento/module-inventory-indexer/etc/queue_consumer.xml                        | inventory.indexer.sourceItem                                                                |
| Queue consumer added     | vendor/magento/module-inventory-indexer/etc/queue_consumer.xml                        | inventory.indexer.stock                                                                     |
| Queue consumer added     | vendor/magento/module-inventory-indexer/etc/queue_consumer.xml                        | inventory.reservations.updateSalabilityStatus                                               |

```

**Comment by norgeindian** [comment]
@convenient , awesome, that would already help a lot and I think with a flag it could be added to the same column. As far as I see, there is no need to have both in the table.
I'm already in contact with @peterjaap , discussing if this might fit better into his tool.
Do you see any way to output the whole command in one, so it can be easily copied directly?
That would then look like:
```
phpstorm.sh diff vendor/magento/module-customer/view/frontend/email/password_reset_confirmation.html app/design/frontend/Ampersand/theme/Magento_Customer/email/password_reset_confirmation.html  vendor_orig/magento/module-customer/view/frontend/email/password_reset_confirmation.html
```
I know, pretty lengthy, but would help me a lot and might it make easier for others as well.

**Comment by peterjaap** [comment]
@convenient but that only has a two-way diff (two filenames in the command)?

**Comment by peterjaap** [comment]
@convenient also see https://github.com/elgentos/magento2-upgrade-gui/issues/4#issuecomment-1268258135

**Comment by norgeindian** [comment]
@convenient , thanks, really cool this way. @peterjaap  also included it in the GUI, so we have it both ways now. Really cool, thanks for implementing that.

**Comment by convenient** [comment]
Let me know how you get on @norgeindian

**Comment by norgeindian** [comment]
@convenient , sorry for coming back to you so late. Just started a new update and currently test the new feature.
One thing, which would be awesome, would be to remove the additional line for Plugins, because there is not much to compare in a three-way diff. As far as I see, it's already not shown for queue consumer changes, but would be awesome to remove it for plugins as well. What do you think? Would you agree? Then I would be happy to provide a PR.

**Comment by convenient** [comment]
@norgeindian Makes sense

I've quite a large refactor going on in this #79 

https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/adfb92c451fc0484398878312a68fb399a2c40e7/src/Ampersand/PatchHelper/Helper/PatchOverrideValidator.php#L259-L262

I guess instead of handling plugin here we can just put a `continue` ?

**Comment by norgeindian** [comment]
@convenient , I agree. A `continue` should be totally fine, as I don't see any useful three-way diff here to use.

**Comment by norgeindian** [comment]
@convenient , sorry, the task is already done, so I currently don't have a fitting testing project.
But will definitely keep it in mind and come back to you as soon as I'm doing the next update. Thanks a lot for your work here.
