### ISSUE TITLE
Report Unnecessary Overrides

### ISSUE THREAD

**Issue by sprankhub** [AmpersandHQ/ampersand-magento2-upgrade-patch-helper#85]
One additional nice feature would be to check for unnecessary overrides. For instance, if `vendor/magento/module-catalog/view/frontend/templates/product/list.phtml` has been overridden in `app/design/frontend/vendor/theme/Magento_Catalog/templates/product/list.phtml` and for whatever reason, both files are now equal (or even better: equal ignoring white space / new line changes), the tool should report this as an issue. The reasoning is that such useless overrides should be removed.

This could potentially not only be helpful for templates, but also other files / types:

- JS files
- `.html` templates under `web/template`
- layout files (via `override` directory)
- e-mail templates?
- preferences in modules (although this probably never happens in reality, so probably okay to skip this one)

I think this would be most helpful for `.phtml` templates, `.html` templates and JS files.

What do you think?

**Comment by convenient** [comment]
@sprankhub Thats a good idea, i feel like we've briefly been down it here maybe https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/issues/13

For `.phtml`, `.js` and`.html` we could pretty easily hack together something which removes all whitespaces, and converts `<?php echo ` into `<?= ` to run a check against, but then we'd miss things like copyright header changes as highlighted in #13.

I'd like to consider some robust way of handling it, I feel like it would need implemented per file type?  I would think something could be done for PHP based files by tokenising them and stripping out any whitespace chars, then comparing the results.
