### ISSUE TITLE
Report Plugins On Non-Existent Classes

### ISSUE THREAD

**Issue by sprankhub** [AmpersandHQ/ampersand-magento2-upgrade-patch-helper#99]
I just updated a project, where I missed quite some customisations. In the project, Klarna was heavily customised. We updated the Klarna module to a new major version, where quite some classes were moved. Hence, some plugins were defined on non-existent classes after the update. I think having plugins on non-existent classes is worth a warning in this module to catch those cases. What do you think?

**Comment by convenient** [comment]
@sprankhub https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/blob/34a19cd6597a51a7eca99bd87c47e9d850daf062/src/Ampersand/PatchHelper/Patchfile/Entry.php#L207-L214

So back in the day when i was putting this together i seem to think that plugins on non existant classes / methods were logged? 🤔 

The current implementation of plugins really relies on the following approach

- Reading the file and after changes to see if any modified functions were `public` and interceptable
- scanning the codebase for anything that plugged into these functions

so i guess maybe we could change this code a little bit if the file had been removed to scan all the interceptable functions from BEFORE the change, and get a list of plugins. and if the file has been removed every one of those plugins needs to be reported.

**Comment by sprankhub** [comment]
I've never seen plugins on non-existent classes / methods being logged. Hence, I think this is a valid use case :) Also, "your plugin will become ineffective" is not a good argument IMHO, because this means you might miss a customisation, which you now need to implement differently.

**Comment by convenient** [comment]
oh yeah totally happy to be improved upon here. I just kind of had the impression that magento made noise about it somewhere, which it seems i was mistaken.
